### ISSUE TITLE
[FEATURE REQUEST] Send failures to slack channel `qa-alerts` and successes to slack channel `qa-reports`

### ISSUE THREAD

**Issue by mkuhn19** [edamametechnologies/threatmodels#72]
# Feature request

## Who is this feature for ?
- EDAMAME Developer

## Tasks
- [ ] if any check fails, send the whole result to `qa-alerts`
- [ ] if all checks pass, send the whole result to `qa-reports`
- [ ] if the semantic is incorrect, send it to `qa-alerts`
